# Generated by Django 4.2.1 on 2023-06-17 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_workdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workdata',
            name='workList',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_data', to='todolist.listdata'),
        ),
    ]
